language: ruby
rvm:
  - 2.6.2

dist: xenial

env:
  - JEKYLL_ENV=production

before_install:
  - sudo apt-get update
  - >-
    sudo apt-get install -y --no-install-recommends
    texlive-latex-base
    texlive-latex-extra
    libpoppler-glib-dev
    imagemagick
    ghostscript
  - sudo rm /etc/ImageMagick-6/policy.xml
  - >-
    pushd /usr/local/src &&
    sudo curl -O -L https://github.com/superruzafa/pdf2svg/archive/master.zip &&
    sudo unzip master.zip &&
    pushd pdf2svg-master &&
    sudo ./configure --prefix=/usr/local &&
    sudo make &&
    sudo make install &&
    popd &&
    popd
  - gem install bundler

install:
  - bundle install

script:
  - bundle exec jekyll build --verbose
  - >-
    bundle exec htmlproofer
    --assume-extension
    --check-favicon
    --check-opengraph
    --url-swap 'https?\:\/\/superruzafa\.github\.io(\:\d+)?:'
    _site

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site/visual-scala-reference
  github_token: $GITHUB_TOKEN
  verbose: true
  on:
    branch: master
