title: Visual Scala Reference
email: superruzafa@gmail.com
description: >-
  An awesome guide to the most common Scala collection functions
baseurl: "/visual-scala-reference"
url: "https://localhost:4000"
github_username:  superruzafa

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
theme: minima
plugins:
exclude:
  - Dockerfile
  - docker-compose.yml
  - docker-compose.override.yml
keep_files:
  - images

collections:
  functions:
    output: true
    permalink: /:title
  es:
    output: true
    permalink: /es/:name

defaults:
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      path: ""
      type: functions
    values:
      lang: en
      layout: function
  - scope:
      path: ""
      type: es
    values:
      lang: es
      layout: function

t:
  en:
    home: ""
    language_name: English
  es:
    home: /es
    language_name: Español
