title: Visual Scala Reference
email: superruzafa@gmail.com
description: >-
  An awesome guide to the most common Scala collection functions
baseurl: "/visual-scala-reference"
url: "https://superruzafa.github.io"
github_username:  superruzafa

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
theme: minima
plugins:
exclude:
  - Dockerfile
  - docker-compose.yml
  - docker-compose.override.yml
keep_files:
  - images

collections:
  functions:
    output: true
