title: Visual Scala Reference
url: https://superruzafa.github.io
baseurl: /visual-scala-reference
destination: ./_site/visual-scala-reference
host: 0.0.0.0

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
theme: minima
plugins:
exclude:
  - Dockerfile
  - docker-compose.yml
  - docker-compose.override.yml
keep_files:
  - images

collections:
  en:
    output: true
    permalink: /:title
  es:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      path: ""
      type: es
    values:
      lang: es
  - scope:
      path: "_en/functions"
    values:
      layout: function
      description: "Graphical representation of the Scala's {{ page.name }} function"
  - scope:
      path: "_es/functions"
    values:
      description: "Representación gráfica de la function {{ page.name }} de Scala"
      layout: function

t:
  en:
    home: ""
    language_name: English
  es:
    home: /es
    language_name: Español
