title: Visual Scala Reference
url: https://superruzafa.github.io
baseurl: /visual-scala-reference
destination: ./_site/visual-scala-reference
host: 0.0.0.0

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
theme: minima
exclude:
  - Dockerfile
  - docker-compose.yml
  - docker-compose.override.yml
keep_files:
  - images

collections:
  en:
    output: true
    permalink: /:title
  es:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
    values:
      home: ""
      lang: en
  - scope:
      path: ""
      type: es
    values:
      home: "/es"
      lang: es
  - scope:
      path: "_en/functions"
    values:
      layout: function
  - scope:
      path: "_es/functions"
    values:
      layout: function
