version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - .:/opt/app
      - vendor:/opt/app/vendor
      - cache:/opt/app/cache

volumes:
  vendor:
  cache:
