version: '3.6'
services:
  site:
    image: visual-scala-reference
    environment:
      - JEKYLL_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
