version: '3.6'
services:
  site:
    command: ["bundle", "exec", "jekyll", "serve", "--config", "_config.yml,_config_dev.yml", "--verbose"]
    environment:
      - JEKYLL_ENV=development
    volumes:
      - .:/site
